### PR TITLE
[*] MO : feeder : fix Context, Shop URL, Logo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@jeromenadaud nobody wants to merge ? :P

**Comment by jnadaud** [comment]
Yes it's seems to  be ok, but why did you remove PrestaShop generator ?

**Comment by ghost** [comment]
ops .. my bad sorry 

(I remove it on my shop couse for security paranoia I prefer to remove info script kiddies could use to attack the shop using a bot ..  forgot to remove this from the PR)

**Comment by ghost** [comment]
@jeromenadaud  fixed, sorry

**Comment by jnadaud** [comment]
I understand.
Thank you for your contribution.

Best regards

**Comment by ghost** [comment]
:+1:

**Pull request merged**
